openapi: 3.1.0
info:
  title: my-app
  description: my-app
  version: 0.2.0
servers:
  - url: 'http://localhost:3000/'
components:
  securitySchemes:
    userID:
      type: apiKey
      name: userId
      in: cookie
      description: The userID used to associate chat history with the user device
  requestBodies:
    chatMessage:
      required: true
      content:
        text/plain:
          schema:
            type: string
security:
  - userID: []
paths:
  /:
    get:
      summary: Get hello message
      description: Returns a simple hello message text
      operationId: Index
      responses:
        200:
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /chat:
    post:
      summary: Create a new chat
      operationId: Chat
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: Sends the input to the AI and streams the response
          content:
            text/plain:
              schema:
                type: string
  /chat/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          content:
            text/plain:
              schema:
                type: string
      summary: Returns the messages associated with the provided chat
      requestBody:
        $ref: '#/components/requestBodies/chatMessage'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
  /message/{id}:
    post:
      summary: Sends a new message to the provided chat
      parameters:
        - name: id
          in: path
          required: true
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        $ref: '#/components/requestBodies/chatMessage'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object


  
